source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "minima", "~> 2.5"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 2.0"
  gem "tzinfo-data"
end

gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

# Only include wdm for supported Ruby versions (< 3.2)
if Gem.win_platform? && RUBY_VERSION < '3.2.0'
  gem "wdm", "~> 0.1.1", :platforms => [:mingw, :mswin, :x64_mingw]
end
